[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.10.8"

[[constraint]]
  name = "github.com/prometheus/alertmanager"
  revision = "0ecc59076ca6b4cbb63252fa7720a3d89d1c81d3"

[[constraint]]
  name = "github.com/weaveworks/common"
  branch = "master"

[[constraint]]
  name = "github.com/weaveworks/promrus"
  version = "v1.0.0-legacy"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[override]]
  name = "github.com/prometheus/common"
  revision = "49fee292b27bfff7f354ee0f64e1bc4850462edf"

[[override]]
  name = "github.com/weaveworks/mesh"
  revision = "5015f896ab62d3e9fe757456c757521ce0c3faff"
