[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.10.8"

[[constraint]]
  name = "github.com/prometheus/alertmanager"
  revision = "fb713f6d8239b57c646cae30f78e8b4b8861a1aa"

[[constraint]]
  name = "github.com/weaveworks/promrus"
  version = "v1.1.0-legacy"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  revision = "a730083cbfbb76e05244f82de0bc4146cb5f79ab"

[[override]]
  name = "k8s.io/client-go"
  revision = "3627aeb7d4f6ade38f995d2c923e459146493c7e"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "75b8dd260ef0469d96d578705a87cffd0e09dab8"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[override]]
  name = "github.com/weaveworks/mesh"
  revision = "5015f896ab62d3e9fe757456c757521ce0c3faff"

# Pin to master branch until there is a more recent stable release:
#   https://github.com/prometheus/client_golang/issues/375
[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"
