[Settings]
# All netfliy options should be defined here. UI options should stay empty.

[build]
base = ""
publish = "website/public"

# Our Makefile build hugo, but it's faster if netlify grab the correct version on their own
# via simple curl.
environment = { HUGO_VERSION="0.59.1" }

# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(env && make web-build || (sleep 30; false)"

[context.deploy-preview]

# NOTE: Sleep at then is to make sure logs are not truncated on error.
command = "(env && make web-build WEBSITE_BASE_URL=${DEPLOY_PRIME_URL}) || (sleep 30; false)"