version: '3.4'
services:

  consul:
    image: consul
    command: [ "agent", "-dev" ,"-client=0.0.0.0", "-log-level=info" ]
    ports:
      - 8500:8500

  swift:
    image: beaukode/docker-swift-onlyone-authv2-keystone
    volumes:
      - .data-swift:/srv:delegated
    ports:
      - 5000:5000
      - 5001:5001
      - 8080:8080
      - 35357:35357

  swift-create-container:
    network_mode: host
    image: theflockers/swiftclient
    environment:
      - OS_USERNAME=admin
      - OS_PASSWORD=s3cr3t
      - OS_TENANT_NAME=admin
      - OS_AUTH_URL=http://localhost:5000/v2.0
      - OS_REGION_NAME=RegionOne
    command: ["sh", "-c", "sleep 30 && swift post cortex-rules && \
                            swift post cortex-tsdb && swift list"]

  prometheus:
    network_mode: host
    image: prom/prometheus:v2.16.0
    command: ["--config.file=/etc/prometheus/prometheus.yaml"]
    volumes:
      - ./config:/etc/prometheus
    ports:
      - 9090:9090

  # Scrape the metrics also with the Grafana agent (useful to test metadata ingestion
  # until metadata remote write is not supported by Prometheus).
  grafana-agent:
    network_mode: host
    image: grafana/agent:v0.2.0
    command: ["-config.file=/etc/agent-config/grafana-agent.yaml", "-prometheus.wal-directory=/tmp"]
    volumes:
      - ./config:/etc/agent-config
    ports:
      - 9091:9091

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - "14268"

  cortex-1:
    network_mode: host
    build:
      context:    .
      dockerfile: dev.dockerfile
    image: cortex
    command: ["sh", "-c", "sleep 40 && exec ./cortex -config.file=./config/cortex.yaml -target=all -server.http-listen-port=8001 -server.grpc-listen-port=9001"]
    depends_on:
      - consul
      - swift
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=cortex-1
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 8001:8001
    volumes:
      - ./config:/cortex/config
      - .data-cortex-1:/data:delegated

  cortex-2:
    network_mode: host
    build:
      context:    .
      dockerfile: dev.dockerfile
    image: cortex
    command: ["sh", "-c", "sleep 40 && exec ./cortex -config.file=./config/cortex.yaml -target=all -server.http-listen-port=8002 -server.grpc-listen-port=9002"]
    depends_on:
      - consul
      - swift
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=cortex-2
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 8002:8002
    volumes:
      - ./config:/cortex/config
      - .data-cortex-2:/data:delegated
