---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configs
  template:
    metadata:
      labels:
        name: configs
    spec:
      containers:
      - name: configs
        image: quay.io/cortexproject/cortex:v1.8.1
        imagePullPolicy: IfNotPresent
        args:
        - -target=configs
        - -server.http-listen-port=80
        - -configs.database.uri=postgres://postgres@configs-db.default.svc.cluster.local/configs?sslmode=disable
        - -configs.database.migrations-dir=/migrations
        ports:
        - containerPort: 80
