---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: query-frontend
  template:
    metadata:
      labels:
        name: query-frontend
    spec:
      containers:
      - name: query-frontend
        image: quay.io/cortexproject/cortex:v1.8.1
        imagePullPolicy: IfNotPresent
        args:
        - -target=query-frontend
        - -log.level=debug
        - -server.http-listen-port=80
        - -server.grpc-listen-port=9095
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 80
          name: http
