---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: query-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: query-frontend
    spec:
      containers:
      - name: query-frontend
        image: quay.io/cortexproject/query-frontend
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        - -server.http-listen-port=80
        - -server.grpc-listen-port=9095
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 80
          name: http
