---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: table-manager
  template:
    metadata:
      labels:
        name: table-manager
    spec:
      containers:
      - name: table-manager
        image: quay.io/cortexproject/cortex:v1.7.1
        imagePullPolicy: IfNotPresent
        args:
        - -target=table-manager
        - -server.http-listen-port=80
        - -dynamodb.url=dynamodb://user:pass@dynamodb.default.svc.cluster.local:8000
        - -schema-config-file=/etc/cortex/schema.yaml
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cortex
      volumes:
        - name: config-volume
          configMap:
            name: schema-config
