auth_enabled: false

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true

ingester:
  max_transfer_retries: 1

  lifecycler:
    # We want to start immediately.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512

    ring:
      kvstore:
        store: consul
        consul:
          host: consul:8500
      replication_factor: 1

querier:
  # Used when the blocks sharding is disabled.
  store_gateway_addresses: store-gateway-1:9008,store-gateway-2:9009

tsdb:
  store_gateway_enabled: true

  dir: /tmp/cortex-tsdb-ingester
  ship_interval: 1m
  block_ranges_period: [ 2h ]
  retention_period: 3h
  backend: s3
  
  bucket_store:
    sync_dir: /tmp/cortex-tsdb-querier
    consistency_delay: 5s

    index_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

    chunks_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

    metadata_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

  s3:
    endpoint:          minio:9000
    bucket_name:       cortex-tsdb
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure:          true

ruler:
  enable_api: true
  storage:
    type: configdb
    configdb:
      configs_api_url: http://configstore:80/

storage:
  engine: tsdb

compactor:
  compaction_interval: 30s
  data_dir:            /tmp/cortex-compactor
  consistency_delay:   1m
  sharding_enabled:    true
  sharding_ring:
    kvstore:
      store: consul
      consul:
        host: consul:8500

store_gateway:
  sharding_enabled: true
  sharding_ring:
    replication_factor: 1
    heartbeat_period:   5s
    heartbeat_timeout:  15s
    kvstore:
      store: consul
      consul:
        host: consul:8500

frontend_worker:
  frontend_address: "query-frontend:9007"
