server:
  log_level: debug
  http_listen_port: 9091

prometheus:
  global:
    scrape_interval: 5s
    external_labels:
      scraped_by: grafana-agent
  configs:
    - name: local
      host_filter: false
      scrape_configs:
        - job_name: tsdb-blocks-storage-s3/distributor
          static_configs:
            - targets: ['distributor:8001']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'
        - job_name: tsdb-blocks-storage-s3/ingester
          static_configs:
            - targets: ['ingester-1:8002', 'ingester-2:8003']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'
        - job_name: tsdb-blocks-storage-s3/querier
          static_configs:
            - targets: ['querier:8004', 'querier-with-scheduler:8013']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'
        - job_name: tsdb-blocks-storage-s3/ruler
          static_configs:
            - targets: ['ruler-1:8021', 'ruler-2:8022']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'
        - job_name: tsdb-blocks-storage-s3/compactor
          static_configs:
            - targets: ['compactor:8006']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'
        - job_name: tsdb-blocks-storage-s3/query-frontend
          static_configs:
            - targets: ['query-frontend:8007', 'query-frontend-with-scheduler:8012']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'
        - job_name: tsdb-blocks-storage-s3/store-gateway
          static_configs:
            - targets: ['store-gateway-1:8008', 'store-gateway-2:8009']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'
        - job_name: tsdb-blocks-storage-s3/query-scheduler
          static_configs:
            - targets: ['query-scheduler:8011']
              labels:
                cluster: 'docker-compose'
                namespace: 'tsdb-blocks-storage-s3'

      remote_write:
        - url: http://distributor:8001/api/v1/push
