global:
  scrape_interval: 5s

scrape_configs:
  - job_name: cortex-distributor
    static_configs:
      - targets: ['distributor:8001']
        labels:
          container: 'distributor'
  - job_name: cortex-ingester-1
    static_configs:
      - targets: ['ingester-1:8002']
        labels:
          container: 'ingester-1'
  - job_name: cortex-ingester-2
    static_configs:
      - targets: ['ingester-2:8003']
        labels:
          container: 'ingester-2'
  - job_name: cortex-querier
    static_configs:
      - targets: ['querier:8004']
        labels:
          container: 'querier'
  - job_name: cortex-ruler
    static_configs:
      - targets: ['ruler:8005']
        labels:
          container: 'ruler'
  - job_name: cortex-compactor
    static_configs:
      - targets: ['compactor:8006']
        labels:
          container: 'compactor'
  - job_name: cortex-query-frontend
    static_configs:
      - targets: ['query-frontend:8007']
        labels:
          container: 'query-frontend'

remote_write:
  - url: http://distributor:8001/api/prom/push
