name: Build Image

on:
  push:
    branches: [ master ]
    paths:
      - 'build-image/**'
      - '.github/workflows/build-image.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'build-image/**'
      - '.github/workflows/build-image.yml'

permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Save image
        run: make save-multiarch-build-image

      - name: Upload Docker Images Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build-image
          path: |
            ./build-image-amd64.tar
            ./build-image-arm64.tar
          if-no-files-found: error

  push:
    needs: build
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && github.repository == 'cortexproject/cortex'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout
        with:
          fetch-depth: 0

      - name: Download Docker Images Artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: build-image

      - name: Load image
        run: make load-multiarch-build-image

      - name: Login to Quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{secrets.QUAY_REGISTRY_USER}}
          password: ${{secrets.QUAY_REGISTRY_PASSWORD}}

      - name: Push image
        run: make push-multiarch-build-image
